### ISSUE TITLE
spidev

### ISSUE THREAD

**Issue by Shahroozgr** [onlaj/Piano-LED-Visualizer#23]
Hi
It's me again :(
Finally I installed all the requirements.txt. But when I run the Visualizer I get the following error message:
File "/home/pi/Piano-LED-Visualizer/visualizer.py" line 3, in <module>
   import LCD_1in44
File "/home/pi/Piano-LED-Visualizer/LCD_1in44.py" line 28, in <module>
   import LCD_Config
File "/home/pi/Piano-LED-Visualizer/LCD_Config.py" line 27, in <module>
   import spidev
ImportError: No module named spidev

Please guide me again
I would be appreciated.

**Comment by CaptainSword123** [comment]
It´s a bit late I know.

I had the same problem. I use python 3, so I install libaries with sudo pip3 install 'Name'

I installed spidev with 

sudo pip3 install spidev

But it still wasn´t working. I had to change

sudo -E python /home/pi/Piano-LED-Visualizer/visualizer.py

into

sudo -E python3 /home/pi/Piano-LED-Visualizer/visualizer.py

it was executed with python 2 instead of 3. Hope it works for you too:)
