### ISSUE TITLE
LEDs don't respond to key press

### ISSUE THREAD

**Issue by hyuny223** [onlaj/Piano-LED-Visualizer#55]
I followed your guide and operated my raspi.
But when I pressed key, LEDs didn't work(but led animation wokred).
So I formatted my sd card and restarted installation. But the result was same.
what's the problem?? any solution?

**Comment by hyuny223** [comment]
my piano has a midi port like this.
is it related to this problem?
![Screenshot_20191228-194029_Samsung Internet](https://user-images.githubusercontent.com/58837749/71542917-d3f0a300-29af-11ea-8815-2aec04bbe9ce.jpg)

**Comment by JAKJUS7** [comment]
Probably. I am not sure, but I think that is like a midi input rather than the output you need for it.

**Comment by onlaj** [comment]
Does your piano work when you connect it to your PC?

**Comment by hyuny223** [comment]
yes. connecting piano to my PC, it worked well.
but when connecting to raspberrypi, it didn't work.
absolutely, i know it was connected because the screen savor worked.

**Comment by hyuny223** [comment]
my piano name is "MPS-120" in kurzweil.

**Comment by hyuny223** [comment]
Is "pip install mido" different from "MIDI Objects for Python" you uploaded in your Youtube?

**Comment by devucsb** [comment]
Having this same issue. Animations working fine, but not responding to keys being pressed. My PC is picking up MIDI from the piano so should be good to send MIDI to RPI. My keyboard has the same MIDI port (printer cable)

**Comment by HansiJung** [comment]
I have the same problem.

LED animation is working.
But no led, when i press a piano key.
What can I change in the set up?

I tryed the USB from the Yamaha piano with my Android tab. 
Piano USB B --> Otg Android tab and the App MIDI keyboard.
If I press a key on the Piano, than I see it in the APP. So I think, that the Piano is sending something.

Can you help.

My daughter is loving that LED, but now I am a looser, because it is not working ;-(

**Comment by devucsb** [comment]
> I have the same problem.
> 
> LED animation is working.
> But no led, when i press a piano key.
> What can I change in the set up?
> 
> I tryed the USB from the Yamaha piano with my Android tab.
> Piano USB B --> Otg Android tab and the App MIDI keyboard.
> If I press a key on the Piano, than I see it in the APP. So I think, that the Piano is sending something.
> 
> Can you help.
> 
> My daughter is loving that LED, but now I am a looser, because it is not working ;-(

go to port settings and refresh ports. After that select your digital piano as the input. With any luck you should be good to go. This tends to happen if the Pi boots up without the piano on so it doesn’t detect the piano while the pi is booting. Let me know if that worked!

**Comment by HansiJung** [comment]
Hi,
after refreshing ports, I choose Input.
There are 3 choices
Midi through: midi through Port-0 14:0
ATRRTMIDIout Client: RTMIDI output 132:0
rtpmidi raspberrypi:Network 128:0

I tried all of them, but it did not work.

**Comment by HansiJung** [comment]
I solved it.
The problem was, that I used the wrong USB port on Raspberry PI Zero.
I did not know, that one is only for power and the other one is the USB port!

Second improvemet was, that i connected the +5V to GIPO 2/4, so do not need an extra 5V USB powersupply.

Thank you very much for the project.
